
tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/certs/broadsea.crt
        keyFile: /etc/certs/broadsea.key

http:
  routers:

    traefik-dashboard:
      entryPoints: '{{ env "HTTP_TYPE" }}'
      service: api@internal
      rule: 'Host(`{{ env "BROADSEA_HOST" }}`) && PathPrefix(`/api`, `/dashboard`)'

    traefik:
      entryPoints: '{{ env "HTTP_TYPE" }}'
      service: "traefik"
      rule: 'Host(`{{ env "BROADSEA_HOST" }}`)'

    broadsea-content:
      entryPoints: '{{ env "HTTP_TYPE" }}'
      service: "broadsea-content"
      rule: 'Host(`{{ env "BROADSEA_HOST" }}`) && PathPrefix(`/`)'
      
    ohdsi-atlas:
      entryPoints: '{{ env "HTTP_TYPE" }}'
      service: "ohdsi-atlas"
      rule: 'Host(`{{ env "BROADSEA_HOST" }}`) && PathPrefix(`/atlas`)'

    ohdsi-webapi:
      entryPoints: '{{ env "HTTP_TYPE" }}'
      service: "ohdsi-webapi"
      rule: 'Host(`{{ env "BROADSEA_HOST" }}`) && PathPrefix(`/WebAPI`)'

    broadsea-hades:
      entryPoints: '{{ env "HTTP_TYPE" }}'
      service: "broadsea-hades"
      rule: 'Host(`{{ env "BROADSEA_HOST" }}`) && PathPrefix(`/hades`)'
      middlewares:
        - "broadsea-hades-root-path-header"
        - "broadsea-hades-path-strip"

    broadsea-solr-vocab:
      entryPoints: '{{ env "HTTP_TYPE" }}'
      service: "broadsea-solr-vocab"
      rule: 'Host(`{{ env "BROADSEA_HOST" }}`) && PathPrefix(`/solr`)'

    broadsea-ares:
      entryPoints: '{{ env "HTTP_TYPE" }}'
      service: "broadsea-ares"
      rule: 'Host(`{{ env "BROADSEA_HOST" }}`) && PathPrefix(`/ares`)'

    # broadsea-arachne-execution-engine:
    #   entryPoints: '{{ env "HTTP_TYPE" }}'
    #   service: "broadsea-arachne-execution-engine"
    #   rule: 'Host(`{{ env "BROADSEA_HOST" }}`) && PathPrefix(`/execution-engine`)'

    broadsea-open-shiny-server:
      entryPoints: '{{ env "HTTP_TYPE" }}'
      service: "broadsea-open-shiny-server"
      rule: 'Host(`{{ env "BROADSEA_HOST" }}`) && PathPrefix(`/shiny`)'
      middlewares: 
        - "broadsea-open-shiny-server-path-strip"

    broadsea-posit-connect:
      entryPoints: '{{ env "HTTP_TYPE" }}'
      service: "broadsea-posit-connect"
      rule: 'Host(`{{ env "BROADSEA_HOST" }}`) && PathPrefix(`/connect`)'

    broadsea-posit-api:
      entryPoints: '{{ env "HTTP_TYPE" }}'
      service: "broadsea-posit-connect"
      rule: 'Host(`{{ env "BROADSEA_HOST" }}`) && PathPrefix(`/__`)'


    # perseus-white-rabbit:
    #   entryPoints: '{{ env "HTTP_TYPE" }}'
    #   service: "perseus-white-rabbit"
    #   rule: 'Host(`{{ env "BROADSEA_HOST" }}`) && PathPrefix(`/white-rabbit`)'
    #   middlewares:
    #   #  - "perseus-white-rabbit-path-strip"
    #     - "perseus-headers"


  middlewares:

    broadsea-hades-path-strip:
      stripPrefix:
        prefixes: 
          - "/hades"
        forceSlash: false

    # perseus-white-rabbit-path-strip:
    #   stripPrefix:
    #     prefixes: 
    #       - "/white-rabbit"
    #     forceSlash: false
    
    # perseus-headers:
    #   headers:
    #     customRequestHeaders:
    #       Host: "https://127.0.0.1"
    #       X-Real-IP: "https://127.0.0.1"
    #       #Host(`{{ env "BROADSEA_HOST" }}`)
    #       #X-Real-IP $remote_addr;
		#       #X-Forwarded-For $proxy_add_x_forwarded_for;
		#       #X-Forwarded-Proto $scheme;
		#       #Host $host;

    broadsea-hades-root-path-header:
      headers:
        customRequestHeaders:
          X-RStudio-Root-Path: "/hades"

    broadsea-open-shiny-server-path-strip:
      stripPrefix:
        prefixes: 
          - "/shiny"
        forceSlash: false

  services:
    traefik:
      loadBalancer:
        servers:
          - url: http://traefik

    broadsea-content:
      loadBalancer:
        servers:
          - url: http://broadsea-content

    ohdsi-atlas:
      loadBalancer:
        servers:
          - url: http://ohdsi-atlas:8080

    ohdsi-webapi:
      loadBalancer:
        servers:
          - url: http://ohdsi-webapi:8080

    broadsea-hades:
      loadBalancer:
        servers:
          - url: http://broadsea-hades:8787

    broadsea-solr-vocab:
      loadBalancer:
        servers:
          - url: http://broadsea-solr-vocab:8983

    broadsea-ares:
      loadBalancer:
        servers:
          - url: http://broadsea-ares

    # broadsea-arachne-execution-engine:
    #   loadBalancer:
    #     servers:
    #       -url: http://broadsea-arachne-execution-engine:8888

    broadsea-open-shiny-server:
      loadBalancer:
        servers:
          - url: http://broadsea-open-shiny-server:3838

    broadsea-posit-connect:
      loadBalancer:
        servers:
          - url: http://broadsea-posit-connect:3939


    # perseus-white-rabbit:
    #   loadBalancer:
    #     servers:
    #       - url: http://perseus-white-rabbit:8000