name: Broadsea Default Profile (Linux and Mac)
on: push
jobs:
  default:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
        httpType: [http, https]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Docker on macOS
        if: runner.os == 'macOS'
        uses: douglascamata/setup-docker-macos-action@v1-alpha
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create certs folder
        run: mkdir -p ./certs
      - name: Replace HTTP_TYPE if https (Linux)
        if: matrix.httpType == 'https' && matrix.os == 'Linux'
        run: sed -i 's/HTTP_TYPE=\"http\"/HTTP_TYPE=\"https\"/g' .env
      - name: Replace HTTP_TYPE if https (Mac)
        if: matrix.httpType == 'https' && matrix.os == 'macOS'
        run: sed -i '' 's/HTTP_TYPE=\"http\"/HTTP_TYPE=\"https\"/g' .env
      - name: Generate certificates for next step
        if: matrix.httpType == 'https'
        uses: kofemann/action-create-certificate@v0.0.4
        with:
          hostcert: 'hostcert.pem'
          hostkey:  'hostkey.pem'
          cachain:  'ca-chain.pem'
      - name: Use generated certificates
        if: matrix.httpType == 'https'
        run: |
          openssl x509 -in hostcert.pem -noout -text
      - name: Build traefik container
        run: docker-compose --env-file .env up -d
      - name: Build default profile
        run: docker-compose --env-file .env --profile default up -d
      - name: Setup postgres client on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get install --yes --no-install-recommends postgresql-client
      - name: Setup postgres client on MacOS
        if: runner.os == 'macOS'
        run: brew install libpq
      - name: Test atlasdb
        run: PGPASSWORD=$(cat ./secrets/webapi/WEBAPI_DATASOURCE_PASSWORD) psql -h 127.0.0.1 -p 5432 -U postgres -c "select source_name from webapi.source limit 1"
      - name: Test traefik container
        run: docker logs traefik
      - name: Test content container
        run: curl -s --retry 10 --retry-connrefused http://127.0.0.1
      - name: Test HADES
        run: curl -s --retry 10 --retry-connrefused http://127.0.0.1/hades/auth-sign-in
      - name: Test Atlas
        run: curl -s --retry 10 --retry-connrefused http://127.0.0.1/atlas/#/home
      - name: Test WebAPI info endpoint
        run: |
          sleep 30
          curl -s --retry 10 --retry-connrefused http://127.0.0.1/WebAPI/info