name: Broadsea Default Profile (Linux and Mac)
on: push
jobs:
  default:
    strategy:
      matrix:
        os: 
          - ubuntu-22.04
          # - macos-12
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Docker on macOS
        if: runner.os == 'macOS'
        uses: douglascamata/setup-docker-macos-action@v1-alpha
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create certs folder
        if: runner.os == 'macOS'
        run: mkdir /Users/runner/work/Broadsea/Broadsea/certs
      - name: Build traefik container
        run: docker-compose --env-file /Users/runner/work/Broadsea/Broadsea/.env up -d
      - name: Build atlasdb profile
        run: |
          docker-compose --env-file /Users/runner/work/Broadsea/Broadsea/.env --profile atlasdb up -d
      - name: Build content profile
        run: docker-compose --env-file /Users/runner/work/Broadsea/Broadsea/.env --profile content up -d
      - name: Build hades profile
        run: docker-compose --env-file /Users/runner/work/Broadsea/Broadsea/.env --profile hades up -d
      - name: Build atlas profile
        run: docker-compose --env-file /Users/runner/work/Broadsea/Broadsea/.env --profile atlas-from-image up -d
      - name: Test atlasdb
        run: |
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends postgresql-client
          pg_isready -d postgres -h 127.0.0.1 -p 5432 -U postgres 
      - name: Build webapi profile
        run: |
          docker-compose --env-file /Users/runner/work/Broadsea/Broadsea/.env --profile webapi-from-image up -d
          sleep 360
      - name: Test traefik container
        run: docker logs traefik
      - name: Test content container
        run: curl -s --retry 10 --retry-connrefused http://127.0.0.1
      - name: Test HADES
        run: curl -s --retry 10 --retry-connrefused http://127.0.0.1/hades/auth-sign-in
      - name: Test Atlas
        run: curl -s --retry 10 --retry-connrefused http://127.0.0.1/atlas/#/home
      - name: Test WebAPI
        run: curl -s --retry 10 --retry-connrefused http://127.0.0.1/WebAPI/info