name: Broadsea Default Profile (Linux and Mac)
on: push
jobs:
  default:
    env:
      ENV_FILE: ./.env
      LOCALHOST_URL: http://127.0.0.1
    strategy:
      matrix:
        os: 
          - ubuntu-22.04
          # - macos-12
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Docker on macOS
        if: runner.os == 'macOS'
        uses: douglascamata/setup-docker-macos-action@v1-alpha
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create certs folder
        run: mkdir -p ./certs
      - name: Build traefik container
        run: docker-compose --env-file $ENV_FILE up -d
      - name: Build atlasdb profile
        run: docker-compose --env-file $ENV_FILE --profile atlasdb up -d
      #- name: Build content profile
      #  run: docker-compose --env-file $ENV_FILE --profile content up -d
      #- name: Build hades profile
      #  run: docker-compose --env-file $ENV_FILE --profile hades up -d
      #- name: Build atlas profile
      #  run: docker-compose --env-file $ENV_FILE --profile atlas-from-image up -d
      #- name: Test atlasdb
      #  run: |
      #    sudo apt-get update
      #    sudo apt-get install --yes --no-install-recommends postgresql-client
      #    pg_isready -d postgres -h 127.0.0.1 -p 5432 -U postgres 
      - name: Build webapi profile
        run: |
          cat ./secrets/webapi/WEBAPI_DATASOURCE_PASSWORD
          docker-compose --env-file $ENV_FILE --profile webapi-from-image up -d
          docker logs ohdsi-webapi
      #- name: Test content container
      #  run: curl -s $LOCALHOST_URL
      #- name: Test HADES
      #  run: curl -s $LOCALHOST_URL
      #- name: Test Atlas
      #  run: curl -s $LOCALHOST_URL/atlas/#/home
      #- name: Test WebAPI
      #  run: curl -s $LOCALHOST_URL/WebAPI/info
      - name: Test traefik container
        run: docker logs traefik