name: Broadsea Default Profile (Linux)
on: push
jobs:
  default:
    strategy:
      matrix:
        os: 
          - ubuntu-22.04
    runs-on: ${{ matrix.os }}
    steps:
      - name: change ip_unprivileged_port_start
        run: sudo sysctl net.ipv4.ip_unprivileged_port_start=80
      - name: Stop Docker daemon
        run: sudo systemctl stop docker
      - name: Start Podman
        run: sudo systemctl enable --now podman.socket
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build traefik container
        run: docker-compose up
      - name: Check traefik container
        run: docker logs traefik
      - name: Build default profile
        run: docker-compose --profile default up
      - name: Test content container
        run: curl -s --retry 10 --retry-connrefused http://127.0.0.1
      - name: Test WebAPI
        run: curl -s --retry 10 --retry-connrefused http://127.0.0.1/WebAPI/info
      - name: Test Atlas
        run: curl -s --retry 10 --retry-connrefused http://127.0.0.1/atlas
      - name: Test HADES
        run: curl -s --retry 10 --retry-connrefused http://127.0.0.1/hades
