name: Broadsea Default Profile (Linux and Mac)
on: push
jobs:
  default:
    env:
      ENV_FILE: ./.env
      LOCALHOST_URL: http://127.0.0.1
    strategy:
      matrix:
        os: 
          - ubuntu-22.04
          - macos-12
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Docker on macOS
        if: runner.os == 'macOS'
        uses: douglascamata/setup-docker-macos-action@v1-alpha
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create certs folder
        run: mkdir -p ./certs
      - name: Build traefik container
        run: docker-compose --env-file .env up -d
      - name: Build default profile
        run: docker-compose --env-file .env --profile default up -d
      - name: Setup postgres client on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get install --yes --no-install-recommends postgresql-client
      - name: Setup postgres client on MacOS
        if: runner.os == 'macOS'
        run: brew install libpq
      - name: Test atlasdb
        run: PGPASSWORD=$(cat ./secrets/webapi/WEBAPI_DATASOURCE_PASSWORD) psql -h 127.0.0.1 -p 5432 -U postgres -c "select * from webapi.source limit 1"
      - name: Test traefik container
        run: docker logs traefik
      - name: Test content container
        run: curl -s --retry 10 --retry-connrefused http://127.0.0.1
      - name: Test HADES
        run: curl -s --retry 10 --retry-connrefused http://127.0.0.1/hades/auth-sign-in
      - name: Test Atlas
        run: curl -s --retry 10 --retry-connrefused http://127.0.0.1/atlas
      - name: Test WebAPI info endpoint
        run: curl -s --retry 10 --retry-connrefused http://127.0.0.1/WebAPI/info