name: Broadsea Default Profile (Linux and Mac)
on: push
jobs:
  default:
    env:
      ENV_FILE: ./.env
      LOCALHOST_URL: http://127.0.0.1
    strategy:
      matrix:
        os: 
          - ubuntu-22.04
          # - macos-12
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Docker on macOS
        if: runner.os == 'macOS'
        uses: douglascamata/setup-docker-macos-action@v1-alpha
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create certs folder
        run: mkdir -p ./certs
      - name: Build traefik container
        run: docker-compose --env-file $ENV_FILE up -d
      - name: Build atlasdb profile
        run: docker-compose --env-file $ENV_FILE --profile atlasdb up -d
      - name: Test atlasdb
        run: |
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends postgresql-client
          PGPASSWORD=$(<./secrets/webapi/WEBAPI_DATASOURCE_PASSWORD) psql -h 127.0.0.1 -p 5432 -U postgres -c "select * from webapi.source limit 1"  