name: Broadsea Default Profile (Linux and Mac)
on: push
jobs:
  default:
    strategy:
      matrix:
        os: 
          - ubuntu-22.04
          - macos-12
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Docker on macOS
        if: runner.os == 'macOS'
        uses: douglascamata/setup-docker-macos-action@v1-alpha
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create certs folder
        if: runner.os == 'macOS'
        run: mkdir /Users/runner/work/Broadsea/Broadsea/certs
      - name: Build traefik container
        run: docker-compose up -d
      - name: Build atlasdb profile
        run: docker-compose --profile atlasdb up -d
      - name: Build content profile
        run: docker-compose --profile content up -d
      - name: Build hades profile
        run: docker-compose --profile hades up -d
      - name: Build atlas profile
        run: docker-compose --profile atlas-from-image up -d
      - name: Build webapi profile
        run: docker-compose --profile webapi-from-image up -d
      - name: Test traefik container
        run: docker logs traefik
      - name: Test content container
        run: curl -s --retry 10 --retry-connrefused http://127.0.0.1
      - name: Test HADES
        run: curl -s --retry 10 --retry-connrefused http://127.0.0.1/hades/auth-sign-in
      - name: Test Atlas
        run: curl -s --retry 10 --retry-connrefused http://127.0.0.1/atlas/#/home
      - name: Debug WebAPI
        run: curl -s --retry 10 --retry-connrefused http://127.0.0.1/WebAPI/info