name: Broadsea Default Profile (Linux)
on: push
jobs:
  default:
    strategy:
      matrix:
        os: 
          - ubuntu-22.04
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: change ip_unprivileged_port_start
        run: sudo sysctl net.ipv4.ip_unprivileged_port_start=80
      - name: Install CNI plugins
        run: |
              sudo curl -O http://archive.ubuntu.com/ubuntu/pool/universe/g/golang-github-containernetworking-plugins/containernetworking-plugins_1.1.1+ds1-1_amd64.deb
              sudo dpkg -i containernetworking-plugins_1.1.1+ds1-1_amd64.deb
              podman system reset --force
      - name: Install Podman Compose
        run: pip3 install https://github.com/containers/podman-compose/archive/devel.tar.gz
      - name: Build traefik container
        run: podman-compose up
      - name: Check traefik container
        run: docker logs traefik
      - name: Build default profile
        run: podman-compose --profile default up
      - name: Test content container
        run: curl -s --retry 10 --retry-connrefused http://127.0.0.1
      - name: Test WebAPI
        run: curl -s --retry 10 --retry-connrefused http://127.0.0.1/WebAPI/info
      - name: Test Atlas
        run: curl -s --retry 10 --retry-connrefused http://127.0.0.1/atlas
      - name: Test HADES
        run: curl -s --retry 10 --retry-connrefused http://127.0.0.1/hades
