name: Broadsea Docker Compose
on: push
jobs:
  traefik:
    strategy:
      matrix:
        os: 
          - ubuntu-22.04
          - macos-12
         # - windows-2022
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Docker on macOS
        if: runner.os == 'macOS'
        uses: douglascamata/setup-docker-macos-action@v1-alpha
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create certs folder
        run: mkdir /Users/runner/work/Broadsea/Broadsea/certs
      - name: Build traefik container
        run: docker-compose up -d
      - name: Check docker container
        run: docker logs traefik
  default:
    strategy:
      matrix:
        os: 
          - ubuntu-22.04
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build traefik container
        run: docker compose up -d
      - name: Build default profile
        run: docker compose --profile default up -d
      - name: Test content container
        run: curl -s --retry 10 --retry-connrefused http://127.0.0.1
      - name: Test WebAPI
        run: curl -s --retry 10 --retry-connrefused http://127.0.0.1/WebAPI/info
      - name: Test Atlas
        run: curl -s --retry 10 --retry-connrefused http://127.0.0.1/atlas
      - name: Test HADES
        run: curl -s --retry 10 --retry-connrefused http://127.0.0.1/hades
