name: Broadsea Docker Compose
on: push
jobs:
  default:
    runs-on: ${{ matrix.os.host }}
    strategy:
      matrix:
        os: [ubuntu-latest, mac-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build default profile
        run: docker-compose --profile default up -d
      - name: Test content container
        run: curl -s --retry 10 --retry-connrefused http://127.0.0.1
