name: Broadsea WebAPI Profile (Linux and Mac)
on: push
jobs:
  webapi_with_ldap:
    strategy:
      matrix:
        os: 
          - ubuntu-22.04
          - macos-12
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Docker on macOS
        if: runner.os == 'macOS'
        uses: douglascamata/setup-docker-macos-action@v1-alpha
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create certs folder
        if: runner.os == 'macOS'
        run: mkdir /Users/runner/work/Broadsea/Broadsea/certs
      - name: Build traefik container
        run: docker-compose up -d
      - name: Check traefik container
        run: docker logs traefik
      - name: Build atlasdb profile
        run: docker-compose --profile atlasdb up -d
      - name: Build openldap profile
        run: docker-compose --profile openldap up -d
      - name: Build webapi profile
        run: WEBAPI_SECURITY_PROVIDER="AtlasRegularSecurity" SECURITY_AUTH_LDAP_ENABLED="true" docker-compose --profile webapi-from-image up -d
      - name: Test WebAPI
        run: curl -s --retry 10 --retry-connrefused http://127.0.0.1/WebAPI/info
      - name: Test WebAPI with LDAP
        run: curl -d "login=user1&password=user1" -X POST http://127.0.0.1/WebAPI/user/login/ldap
      
